const economyTips=["Lave roupas apenas com a máquina cheia 🧺", "Tome banhos de no máximo 5 minutos 🚿",
"Troque lâmpadas comuns por LED 💡", "Desligue aparelhos da tomada ao sair 🔌",
"Use cores claras nas paredes internas 🎨", "Instale arejadores nas torneiras 🚰",
"Limpe o filtro do ar-condicionado ❄️", "Passe grandes quantidades de roupa de uma vez 👔",
"Cancele streamings que não assiste 📺", "Reveja seu plano de internet anualmente 🌐",
"Peça desconto na anuidade do cartão 💳", "Opte por bancos digitais sem tarifas 📱",
"Conserte vazamentos imediatamente 💧", "Use a tampa da panela para poupar gás 🍳",
"Aproveite a luz natural do dia ☀️", "Organize a despensa para não repetir itens 🥫",
"Faça pequenos reparos com tutoriais 🛠️", "Acumule a louça para lavar de uma só vez 🍽️",
"Use o modo 'Eco' dos aparelhos 🌱", "Reduza a temperatura do chuveiro no verão 🌡️",
"Faça uma lista antes de sair de casa 📝", "Nunca vá ao mercado com fome 🍎",
"Priorize as marcas próprias do mercado 🏷️", "Compre frutas e legumes da estação 🍇",
"Compare o preço por quilo ou litro ⚖️", "Evite alimentos ultraprocessados 🚫",
"Cozinhe em grandes quantidades e congele 🧊", "Substitua carne por proteína vegetal 🥦",
"Leve marmita para o trabalho 🍱", "Faça sua própria horta de temperos 🌿",
"Evite comprar bebidas em restaurantes 🥤", "Aproveite dias de promoção de hortifrúti 🥕",
"Compre itens não perecíveis em atacado 📦", "Olhe sempre as prateleiras inferiores 👇",
"Use sobras para criar novas receitas 🥘", "Prepare seu café em casa ☕",
"Higienize alimentos para durarem mais 🧼", "Faça pão e bolos de forma caseira 🍞",
"Evite comprar água mineral na rua 💧", "Use sacolas reutilizáveis para evitar taxas 🛍️",
"Mantenha os pneus sempre calibrados 🚗", "Evite frenagens bruscas para poupar ⛽",
"Utilize aplicativos de carona 🤝", "Use bicicleta para trajetos curtos 🚲",
"Faça manutenção preventiva no carro 🔧", "Caminhe mais para economizar e ter saúde 🏃",
"Use postos com programas de pontos ⛽", "Retire peso desnecessário do porta-malas 🧳",
"Use transporte público fora do pico 🚌", "Planeje rotas para evitar o trânsito 🗺️",
"Viaje em baixa temporada ✈️", "Reserve passagens com antecedência 🎟️",
"Aguarde 24h antes de comprar ⏱️", "Use cupons de desconto online 🎟️",
"Compre roupas em brechós de qualidade 👗", "Participe de grupos de trocas 🔄",
"Evite seguir perfis de luxo excessivo 📲", "Planeje presentes com antecedência 🎁",
"Desative notificações de apps de compras 🔕", "Prefira qualidade em vez de quantidade ✨",
"Diga 'não' para eventos sociais caros 🙅‍♂️", "Pague à vista para ter desconto 💵",
"Use cashback em todas as compras 💰", "Alugue itens de uso esporádico 🔨",
"Corte o hábito de comprar por estresse 🧠", "Analise o custo por uso da peça 🧥",
"Conserte sapatos em vez de descartar 👞", "Customize roupas antigas ✂️",
"Anote todos os seus gastos diários 📒", "Crie sua reserva de emergência 🆘",
"Estabeleça metas financeiras claras 🎯", "Invista assim que o salário cair 📈",
"Automatize suas aplicações mensais 🤖", "Estude sobre educação financeira 📚",
"Evite o cheque especial sempre 🚫", "Não empreste seu cartão para outros 🙅",
"Use a regra do 50-30-20 📊", "Revise seus extratos toda semana 🔍",
"Pague contas em dia para evitar juros 📅", "Busque fontes de renda extra 💸",
"Defina limite de gastos para o lazer 🍿", "Converse sobre dinheiro em família 👨‍👩‍👧",
"Compare taxas de corretoras 🏦", "Reinvista os dividendos recebidos 🔄",
"Dilua shampoos muito densos 🧴", "Use protetor solar para evitar doenças 🧴",
"Corte tubos de creme para o fim ✂️", "Exerça-se ao ar livre em parques 🌳",
"Pinte as unhas e cuide-se em casa 💅", "Use livros de bibliotecas públicas 📖",
"Aprenda costura para pequenos ajustes 🧵", "Troque presentes por experiências 🎡",
"Beba água para evitar lanches extras 💧", "Lave seu próprio carro no domingo 🧼",
"Use vinagre e bicarbonato na limpeza 🧼", "Venda o que está parado em casa 📦",
"Aproveite shows e museus gratuitos 🎭", "Cancele seguros que não fazem sentido 📄",
"Foque no propósito e não no status 💎", "Comemore vitórias sem gastar muito 🥂",
"Pare de fumar ou reduza vícios 🚬", "Use apps de controle de saúde gratuitos 📱",
"Aproveite programas de milhas ✈️", "Compre eletrônicos em datas promocionais 📱",
"Use o buscador de preços do Google 🔍", "Corte o próprio cabelo ou franja ✂️",
"Faça um bazar com amigos 👗", "Divida assinaturas familiares 👨‍👩‍👦",
"Use repelente natural 🦟", "Reaproveite potes de vidro 🫙",
"Faça compostagem doméstica 🍎", "Desligue o Wi-Fi ao viajar 📶",
"Use sabão em barra para render mais 🧼", "Evite o uso de papel toalha 🧻",
"Pratique o minimalismo 🧘", "Revise seus seguros anualmente 📝","💡 Guarde 10% do que recebe.", "💡 Evite parcelas longas.", "💡 Pague contas em dia.", "💡 Revise gastos fixos.","💡 Pesquise preços em diferentes lojas antes de fechar qualquer compra", "💡 Destine uma porcentagem fixa do seu salário para a reserva de emergência", "💡 Evite fazer compras no supermercado quando estiver com fome", "💡 Desconecte os aparelhos eletrônicos da tomada quando não estiverem em uso", "💡 Priorize o pagamento de dívidas com os juros mais altos primeiro", "💡 Substitua lâmpadas incandescentes por modelos de LED mais eficientes", "💡 Planeje suas refeições da semana para evitar gastos excessivos com delivery", "💡 Monitore seus gastos diários em um aplicativo ou planilha financeira", "💡 Aproveite ao máximo a iluminação natural abrindo janelas e cortinas", "💡 Avalie se você realmente utiliza todas as suas assinaturas de streaming", "💡 Prefira pagar suas compras no Pix ou débito para ganhar descontos", "💡 Mantenha a manutenção do seu carro em dia para economizar combustível", "💡 Use cupons de desconto e programas de cashback sempre que possível", "💡 Estabeleça um limite máximo para gastos com lazer e entretenimento", "💡 Reduza o tempo do banho para economizar água e energia elétrica"];